model:
  base_learning_rate: 1e-4
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 1
    lossconfig:
      target: ldm.modules.losses.mdct.MdctLoss
      params:
        kl_weight: 0.00001

    ddconfig:
      double_z: True
      z_channels: 1
      resolution: 256
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 12
    wrap: True
    train:
      target: ldm.data.mtg.MtgMdct
      params:
        split: train
        size: 256
        sampling_rate: 22050
    validation:
      target: ldm.data.mtg.MtgMdct
      params:
        split: valid
        size: 256
        sampling_rate: 22050

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 100
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
